# Generated by Django 5.1 on 2024-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=20)),
                ('start_time', models.TimeField()),
                ('lauch_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendar'), ('canceled', 'Cancelar'), ('completed', 'Completo')], default='scheduled', max_length=10),
        ),
    ]
