# Generated by Django 5.1 on 2024-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_schedules_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='lauch_time',
        ),
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'Sabado'), ('Sunday', 'Domingo')], max_length=20),
        ),
    ]
