# Generated by Django 5.1 on 2024-09-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_remove_schedules_lauch_time_alter_schedules_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.service'),
        ),
    ]
