# Generated by Django 5.1 on 2024-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_appointment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='launch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendar'), ('Cancelado', 'Cancelar'), ('Finalizado', 'Completo')], default='Agendado', max_length=10),
        ),
    ]
