# Generated by Django 5.1 on 2024-09-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_schedules_launch_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='launch',
            new_name='launch_time',
        ),
    ]
