# Generated by Django 5.1 on 2024-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_rename_launch_schedules_launch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'SABADO'), ('Sunday', 'Domingo')], max_length=20),
        ),
    ]
